### ISSUE TITLE
Recursive rfolder

### ISSUE THREAD

**Issue by chrisirhc** [quarterpast/rfolderify#3]
Thanks for your plugin!

I was thinking it could also be useful to do recursive includes. The module object will still be flat but it would be to path to the file like:

```
myfolder
├── x.js
└── y
    └── z.js
```

`rfolder('./myfolder')` would return module like:

```
{
  'x': …, // module of x.js
  'y/z': …  // module of y/z.js
}
```

This could be opt-in, like `rfolder('./myfolder', true)`.

**Comment by apaleslimghost** [comment]
This package isn't well-maintained. I don't have a lot of time for implementing new features. I'd welcome a pull request, or you could use [bulkify](https://www.npmjs.com/package/bulkify).
